/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals;

import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.WHITE;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.RoundRectangle2D;

public class AccountType extends javax.swing.JFrame {
    public AccountType() {
        setUndecorated(true);//this removes the outside frame(Outline, minimize, maximize and exit)
        initComponents();
        setLocationRelativeTo(null); 
        setSize(800, 500); 
        pack(); 
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20)); 
        getContentPane().setBackground(Color.white);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exitframe = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Header = new javax.swing.JLabel();
        Medicalpanel = new javax.swing.JPanel();
        Medicallbl = new javax.swing.JLabel();
        Doctorimg1 = new javax.swing.JLabel();
        Patientpanel = new javax.swing.JPanel();
        Patientlbl = new javax.swing.JLabel();
        Patientimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Exitframe.setBackground(new java.awt.Color(255, 255, 255));

        Exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Exit.setText("X");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitframeLayout = new javax.swing.GroupLayout(Exitframe);
        Exitframe.setLayout(ExitframeLayout);
        ExitframeLayout.setHorizontalGroup(
            ExitframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitframeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ExitframeLayout.setVerticalGroup(
            ExitframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        Header.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        Header.setForeground(new java.awt.Color(16, 156, 252));
        Header.setText("Choose Account Type");

        Medicalpanel.setBackground(new java.awt.Color(255, 255, 255));
        Medicalpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Medicallbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Medicallbl.setText("Medical Professional");
        Medicalpanel.add(Medicallbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        Doctorimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Doctor1.png"))); // NOI18N
        Doctorimg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Doctorimg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Doctorimg1MouseExited(evt);
            }
        });
        Medicalpanel.add(Doctorimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        Patientpanel.setBackground(new java.awt.Color(255, 255, 255));
        Patientpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Patientlbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Patientlbl.setText("Patient");
        Patientpanel.add(Patientlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        Patientimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Patient.png"))); // NOI18N
        Patientimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PatientimgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PatientimgMouseExited(evt);
            }
        });
        Patientpanel.add(Patientimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exitframe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Medicalpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(Patientpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(Header)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Exitframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Header)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Medicalpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Patientpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
       Color hoverColor = Color.RED;
       Exitframe.setBackground(hoverColor);
       Exit.setForeground(WHITE);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
       Color defaultColor = Color.WHITE;
        Exitframe.setBackground(defaultColor);
        Exit.setForeground(BLACK);
    }//GEN-LAST:event_ExitMouseExited

    private void Doctorimg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Doctorimg1MouseEntered
        Color hoverColor = Color.BLUE;
        Medicallbl.setForeground(hoverColor);
    }//GEN-LAST:event_Doctorimg1MouseEntered

    private void Doctorimg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Doctorimg1MouseExited
         Color defaultColor = Color.BLACK;
         Medicallbl.setForeground(defaultColor);
    }//GEN-LAST:event_Doctorimg1MouseExited

    private void PatientimgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientimgMouseEntered
        Color hoverColor = Color.BLUE;
        Patientlbl.setForeground(hoverColor);
    }//GEN-LAST:event_PatientimgMouseEntered

    private void PatientimgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientimgMouseExited
         Color defaultColor = Color.BLACK;
         Patientlbl.setForeground(defaultColor);
    }//GEN-LAST:event_PatientimgMouseExited
     
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountType().setVisible(true);
            }
        });
    }
    private int radius =0;
    protected void Join(Graphics grphcs){
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.fillRoundRect(0,0,getWidth(),getHeight(),radius,radius);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Doctorimg1;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel Exitframe;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Medicallbl;
    private javax.swing.JPanel Medicalpanel;
    private javax.swing.JLabel Patientimg;
    private javax.swing.JLabel Patientlbl;
    private javax.swing.JPanel Patientpanel;
    // End of variables declaration//GEN-END:variables

    void setVisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
